### ISSUE TITLE
How to disable the keymap on an event?

### ISSUE THREAD

**Issue by nilshae** [Dafrok/v-hotkey#10]
I have a Vuetify `<v-text-field></v-text-field>` and I want to disable the keymap for the time the text field has the focus. I tried to change the to change the computed keymap based on text fields state like this:

```
get keymap() {
    if (textFieldActive) {
      return;
    }

    return {
      // ... my default keymap
    };
  }
```
The correct return statement is called, but the keybindings are still active. If I try to override the keybindigs, both the old an new one get executed. What do I miss?

**Comment by Dafrok** [comment]
1. set a flag to disable the handler when focus on input
2. stop propagation
etc.
