### ISSUE TITLE
trigger when specific element has focused

### ISSUE THREAD

**Issue by RezaErfani67** [Dafrok/v-hotkey#13]
suppose i have two drop down...
i want if focus was on dropdown 1 , function1 run with Enter
if focus was on dropdown2, function2 run with Enter

**Comment by guille-moe** [comment]
Not sure what your code look like but you can bind `v-hotkey` twice for the same key, so you can wrap your `function1` and check if your `dropdown1` is focus before run it, and do the same for `dropdown2`.

**Comment by Dafrok** [comment]
sure, bind twice for same key, clear the keymap which you won't trigger it.
