### ISSUE TITLE
"?" can't be assigned?

### ISSUE THREAD

**Issue by kdekooter** [Dafrok/v-hotkey#14]
I have the following keymap:
```
    keymap() {
      return {
        '?': this.showHotKeyHelp,
        '/': this.goToSearch
      }
    }
```
The `/` is working fine. However `?` does not do anything.

**Comment by Dafrok** [comment]
You should try `shift+/` instead

**Comment by kdekooter** [comment]
That would work for a US keyboard layout. But how about e.g. German or French layouts?

**Comment by Dafrok** [comment]
Browser doesn't have any ability to detect keyboard layout, and no one can promise there's no conflicts between different layouts, so I consider adding an option to allow users to set their custom keycode map alias, how do you like it?

**Comment by kdekooter** [comment]
It would be great if you could map to a character, regardless of the keyboard (and modifier keys).

**Comment by Dafrok** [comment]
This featrue has been resolved in version 0.6.0, cheers.

> ce5f323ce2676854b506691ab9398b2ba0356925

**Comment by kdekooter** [comment]
I am sorry @Dafrok, but it does not seem to work as expected. As per the readme, I added this option to the setup code:

```
Vue.use(VueHotkey, {
  '①': 63 // question mark
})
```
And in my component, I added this alias to the keymap:
```
 {
  '①': this.showHotKeyHelp
 }
```
The method is not being triggered... Am I missing something?

**Comment by Dafrok** [comment]
https://codesandbox.io/s/vue-template-rg1wp

I've written a example and it works well

**Comment by kdekooter** [comment]
So if I understand correctly, in this example pressing the "1" key should toggle "Hoory"? 

Not working for me on any of my browsers: Firefox, Safari and Chrome.

**Comment by Dafrok** [comment]
The keycode of charactor `1` is 49, It's my fault.

**Comment by Dafrok** [comment]
I've no idea about your keyborad layout, try to open a blank page, input `document.onkeydown = e => console.log(e.keyCode)` to console, and then press `?`, tell me the output

**Comment by kdekooter** [comment]
On my US keyboard I have to press Shift+/ to get a question mark. Does that mean that ASCII code 63 is not detected in that case?

**Comment by Dafrok** [comment]
Finally I catch the problem, the hotkeys triggers by a specified **keycode** instead of a **character**.
The keydown & keyup event pass me not only an ASCII code as `event.keyCode` representing the original character without holding shift key, but also current charactor as `event.key`. You needs to trigger the hotkey by a charactor, not an ASCII code, but matching both `event.keyCode` and `event.key` may cause some conflicts.
I think it needs two matching modes probably, but I haven't thought of how to design this feature yet. Do you have any ideas?

**Comment by kdekooter** [comment]
Take a look at https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent. I played around with the linked CodePen a bit - see: https://codepen.io/kdekooter/pen/ydQNoZ

As you can see Alt/Ctrl/Meta are only detected on KeyPress. Shift and single characters are detected both on KeyPress and KeyUp.

Maybe in case of a single character mapping -  you should intercept KeyUp and check `key` and in case of some combination (`Ctrl-C`, `Alt-F4` etc) intercept KeyUp and check the `key` _and_ the modifiers (`shiftKey/altKey/ctrlKey/metaKey`)?
