### ISSUE TITLE
How to prevent key from being intercepted by v-hotkey when focus is in an editable field?

### ISSUE THREAD

**Issue by kdekooter** [Dafrok/v-hotkey#15]

**Comment by Dafrok** [comment]
stop events propagation to the document

**Comment by kdekooter** [comment]
do you mean in the editable field?

**Comment by Dafrok** [comment]
whether editable or not, just stop propagation

**Comment by kdekooter** [comment]
shouldn't this be handled in v-hotkey instead of in every component that could possibly emit keystrokes?

**Comment by Dafrok** [comment]
There r such a lot of ways catch your case, check tag names of event target or set the stop propagation handler on parent elements

**Comment by kdekooter** [comment]
My case? Seems like a use case _every_ user of this library is going to face. So it would be great if v-hotkey supports this.

**Comment by Dafrok** [comment]
But it's a feature, you can't guarantee that whether other users want to use custom shortcuts in input elements or not.

**Comment by Dafrok** [comment]
I have added a syntactic sugar as regular `stop` modifier in the next version, I hope it will save time bro.
