### ISSUE TITLE
[Vue warn]: Error in directive hotkey componentUpdated hook: "TypeError: Cannot read property 'value' of undefined"

### ISSUE THREAD

**Issue by peda** [Dafrok/v-hotkey#16]
Sometimes it would be neat to declare the hotkey binding inline (in the tag) - especially when you only have one binding. But in this case the error message `[Vue warn]: Error in directive hotkey componentUpdated hook: "TypeError: Cannot read property 'value' of undefined"` is thrown. 

```
<my-tag v-hotkey="{ esc: cancelEdit }">
...
</my-tag>
```

When I use a computed (or data) variable instead of `{ esc: cancelEdit }` everything works fine.

**Comment by LeCoupa** [comment]
@peda Your code was working with version `0.3.1`. Just updated the package to 0.6.0 and I get the same issue.

**Comment by zcuric** [comment]
I encountered the same issue. It looks like `v-hotkey` needs a computed property to function without throwing an error. 

This still works, but error is being thrown.

**Comment by LeCoupa** [comment]
Yes, we ended up using a computed property everywhere to keep updating this package to its latest version.

**Comment by zcuric** [comment]
#20 solves this.
