### ISSUE TITLE
How to handle 'ctrl + left'?

### ISSUE THREAD

**Issue by DenniLa2** [Dafrok/v-hotkey#19]
Hello
thanks for v-hotkey!
How to handle combination 'ctrl+left'? In chrome fire only 'left' without 'ctrl'

**Comment by Dafrok** [comment]
This key combination is conflicted with operation system, at least in Mac OSX. I guess browsers is not avalible of preventing system actions.

**Comment by Dafrok** [comment]
This key combination is conflicted with operation system, at least in Mac OSX. I guess browsers is not able to block system behaviors.

**Comment by zcuric** [comment]
Yes, MacOS uses `ctrl + arrow` to move from one desktops. Combination of `ctrl+ arrows` is usually a OS specific shortcut that browser cannot intercept.  

@Dafrok please close this issue.
