### ISSUE TITLE
Share demo source

### ISSUE THREAD

**Issue by hatboysam** [Dafrok/v-hotkey#30]
The demo is really nice but I can't find the un-minified source anywhere.  Specifically I'd like to see how this page was implemented:
https://dafrok.github.io/v-hotkey/#/step/5

Could you open-source the demo as well?

**Comment by vladimyr** [comment]
@hatboysam Is this what you are looking for https://github.com/Dafrok/v-hotkey/tree/master/src/docs

**Comment by samtstern** [comment]
D'oh!  Yes it is
