### ISSUE TITLE
NPM Package is outdated

### ISSUE THREAD

**Issue by tonimc** [Dafrok/v-hotkey#36]
Dealing with a problem using `v-hotkeys` I've noticed that the code of the `v0.8.0` is different from the code on the master branch of the project. The outdate is since the latest commits from Sept 3th, 2020, for example, [this commit](https://github.com/Dafrok/v-hotkey/commit/02d45f27954320f0b5152b1e07d01d32a1569bb6#diff-27653c212e1cfe533e4eb2f7d0d3f89604c9de48a09583b4cbbbcbd08a07da79) is not included on the `v0.8.0`

Could be possible to create a `v0.8.1` (or `v0.9.0`) with the latest improvements? Maybe there is a reason for not update the npm package but I think that users could keep using `v0.8.0` if they prefer.

Thanks for your time.

**Comment by tonimc** [comment]
@Dafrok @zcuric Taking a look to other issues, I think that issues #33 and #29 could be related to this. In the current npm package when the active element is an `input` the hotkeys are not avoided, the user has to use the modifier `stop` for that 

https://github.com/Dafrok/v-hotkey/blob/7e8758475ab6bbc1643864516f757a8bb4a428a8/src/main.js#L7-L17 

The documentation explains that the `stop` modifier is to stop the propagation and that is how it works in master but not in the `v0.8.0`.

Thanks for your time.

**Comment by Dafrok** [comment]
Thank you for reminding me, new version has been published now
