### ISSUE TITLE
How to override hotkeys in child component?

### ISSUE THREAD

**Issue by nzxt** [Dafrok/v-hotkey#5]
#### How can i reassign or override keymap of parent component in the child component? Is it possible?
I have a large application and in some places i need to bind same hotkey for different actions. 
Then i'm in parent window i need to bind _'enter'_ for one method and in child dialog i need another action.
Thanks!

**Comment by Dafrok** [comment]
Just stop the propagation

**Comment by nzxt** [comment]
Can you show simple code sample on how to stopPropogation? How/where can i catch the event?

**Comment by Dafrok** [comment]
I would coding like this if I were you:

```vue
<template>
<Parent v-hotkey="keyMap">
  <Children v-if="active"></Children>
</Parent>
</template>

<script>
return {
  data () {
    return {active: false}
  },
  computed () {
    keyMap () {
      return {
        'ctrl+s': function () {
          if (this.active) return
          // do something
        }
      }
    }
  }
}
</script>
```
