### ISSUE TITLE
Possible to make event.preventDefault() into an option?

### ISSUE THREAD

**Issue by san-kumar** [Dafrok/v-hotkey#7]
Right now a lot of shortcuts like `Ctrl+S`, `Ctrl+R`, etc trigger the default browser behavior. When mapped to custom hotkeys the programmer generally would want to skip this for which we can call `event.preventDefault();`

But I was thinking that we can add a modifier like this to make this the default behavior and save some extra code like this:

```
<template>
  <span v-hotkey.prevent="keymap" v-show="show">Not the .prevent</span>
</template>

```

What do you guys think?

**Comment by pkMinhas** [comment]
@san-kumar, were you able to fix this in your app? Can you share the solution?

**Comment by Dafrok** [comment]
LGTM, would you work for that feature?
