### ISSUE TITLE
Is it possible to load keymap dynamically?

### ISSUE THREAD

**Issue by amirshawn** [Dafrok/v-hotkey#9]
I'm curious if there's a way to load the keymap dynamically from an object?  If so what would work for that?

Here is what I've tried, it creates the object but it doesn't trigger the function:

```
keymap () {
  var jsonObj = {};
  for(var i=0; i<this.shipping_presets.length; i++){
    jsonObj[this.shipping_presets[i].hotkey.title] = this.selectPreset;
  }
   return jsonObj;
},
```

Thank you for your help!

**Comment by amirshawn** [comment]
I figured it out!  I just needed to create a seperate component and use a v-if to mount the component once the data from the database was done loading.  Now I'm able to pass the keyboard event back to the parent.  Thank you for your plugin!

**Comment by Dafrok** [comment]
Dynamic keymap as a feature sounds useful, I'll have a try to implement it.

**Comment by amirshawn** [comment]
Yeah, it's definitely a necessity!  It seems to be working great as is though as long as you wrap the hotkey computed properties in a component and don't render it until all the database data is loaded.  It probably could be done in a more elegant way though.  I'm interested in seeing how you approach it.

**Comment by Dafrok** [comment]
Hello there, dynamic keymaps has been supported @0.3.0 version, enjoy it!

**Comment by amirshawn** [comment]
Hi Dafrok, 
Thank you for implementing that.  Do you have a code example of how to implement that?
Thank you,
Amir

**Comment by Dafrok** [comment]
Change the return value of keymap properties, without anything else.

**Comment by Dafrok** [comment]
Examples in the docs https://github.com/Dafrok/v-hotkey/blob/master/docs/src/pages/step-6.vue#L48-L60
